name: 'Get and cache dependencies'
description: 'An action to get and cache dependencies'
inputs:
  caching:
    description: 'Whether to cache dependencies'
    required: false
    type: boolean
    default: true
runs:
  using: 'composite'
  steps:
      - name: Cache pip packages
        if: inputs.caching == true
        id: cache-pip
        uses: actions/cache@v4.2.4
        with:
          path: ~/.local
          key: pip-${{ runner.os }}-py3.13-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies
        if: steps.cache-pip.outputs.cache-hit != 'true' || inputs.caching == false
        run: pip install --user -r requirements.txt
        shell: bash