name: Run Tests
on: 
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - main
      - feat/**
    paths-ignore:
      - '.github/workflows/*'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0
      - name: Set up Python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: '3.13'
          cache: 'pip'
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Set up Python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest
  deploy:
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0
      - name: Set up Python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Deploy application
        run: echo "Deploying application..."