name: Deployment Pipeline
on: 
  pull_request:
    types: [opened, reopened]

  push:
    branches:
      - main
      - feat/**
    paths-ignore:
      - '.github/workflows/*'

  workflow_dispatch:

env:
  WORKFLOW_LEVEL_ENV: workflow

jobs:
  lint:
    environment: sample_env
    env:
      JOB_LEVEL_ENV: lint
      GITHUB_SECRET: ${{ secrets.MY_SECRET }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Set up Python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: '3.13'

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Set up Python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: '3.13'

      - name: Cache virtual environment
        id: cache-venv
        uses: actions/cache@v4.2.4
        with:
          path: |
            .venv
            ~/.cache/pip
          key: venv-${{ runner.os }}-py3.13-${{ hashFiles('**/requirements.txt') }}

      - name: Create and activate virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'

      - name: Create reports directory
        run: mkdir -p reports

      - name: Run tests
        id: run_tests
        run: pytest --html=reports/pytest-report.html --self-contained-html

      - name: Upload Test Report
        if: failure() && steps.run_tests.outcome == 'failure'
        uses: actions/upload-artifact@v4.3.3
        with:
          name: test-report
          path: reports/pytest-report.html
          if-no-files-found: error
          
  deploy:
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Set up Python  
        uses: actions/setup-python@v6.0.0
        with:
          python-version: '3.13'
      
      - name: Cache virtual environment
        id: cache-venv
        uses: actions/cache@v4.2.4
        with:
          path: |
            .venv
            ~/.cache/pip
          key: venv-${{ runner.os }}-py3.13-${{ hashFiles('**/requirements.txt') }}

      - name: Create and activate virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'

      - name: Deploy application
        run: |
          source .venv/bin/activate
          echo "Deploying application..."

  report:
    needs: [test, lint, deploy]
    if: failure()
    runs-on: ubuntu-latest
    
    steps:
      - name: Generate Report
        run: |
          echo "Generating report for failed jobs..."
          echo "${{ toJSON(github) }}"