name: Deployment Pipeline
on: 
  pull_request:
    types: [opened, reopened]

  push:
    branches:
      - main
      - feat/**
    paths-ignore:
      - '.github/workflows/*'

  workflow_dispatch:

env:
  WORKFLOW_LEVEL_ENV: workflow

jobs:
  lint:
    environment: sample_env
    env:
      JOB_LEVEL_ENV: lint
      GITHUB_SECRET: ${{ secrets.MY_SECRET }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Set up Python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: '3.13'

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

  test:
    continue-on-error: true
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
        operating-system: [ubuntu-latest, ubuntu-22.04]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Set up Python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip packages
        id: cache-pip
        uses: actions/cache@v4.2.4
        with:
          path: ~/.local
          key: pip-${{ runner.os }}-py3.13-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies
        if: steps.cache-pip.outputs.cache-hit != 'true'
        run: pip install --user -r requirements.txt

      - name: Create reports directory
        run: mkdir -p reports

      - name: Run tests
        id: run_tests
        run: pytest --html=reports/pytest-report.html --self-contained-html

      - name: Upload Test Report
        if: failure() && steps.run_tests.outcome == 'failure'
        uses: actions/upload-artifact@v4.3.3
        with:
          name: test-report
          path: reports/pytest-report.html
          if-no-files-found: error
          
  deploy:
    needs: [test, lint]
    uses: ./.github/workflows/reusable_deploy.yml
    
  report:
    needs: [test, lint, deploy]
    if: failure()
    runs-on: ubuntu-latest

    steps:
      - name: Generate Report
        run: |
          echo "Generating report for failed jobs..."
          echo "${{ toJSON(github) }}"