name: Reusable Deploy Workflow
on: 
  workflow_call:
    inputs:
      deploy_parameter:
        description: 'Some deploy parameter'
        required: false
        type: string
        default: 'default_value'
    outputs:
      deploy_output:
        description: 'Output from deploy job'
        value: ${{ jobs.deploy.outputs.deploy_output }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      deploy_output: ${{ steps.set_output.outputs.deploy_output }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Set up Python  
        uses: actions/setup-python@v6.0.0
        with:
          python-version: '3.13'
          
      - name: Get and cache dependencies
        uses: ./.github/actions/cached_deps

      - name: Deploy application
        run: echo "Deploying application with parameter ${{ inputs.deploy_parameter }}..."

      - name: Set output
        id: set_output
        run: echo "deploy_output=Deployment successful!" >> $GITHUB_OUTPUT