name: Run Tests
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v5.0.0

            - name: Set up Python
              uses: actions/setup-python@v6.0.0
              with:
                  python-version: '3.13'

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Run tests
              run: pytest